### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by sansha** [sansha/led-blaster#1]
while compiling many errors occur....
I don't know why...
Daniel, as you did the last changes:
Are there any other compiler arguments I need to use?
Or is there any bug?

**Comment by dabch** [comment]
i haven't done any changes since Sep 9....

**Comment by sansha** [comment]
I fixed it on my pi but haven't pushed it already.

David Buch notifications@github.com schrieb am So., 13. Sep. 2015 12:39:
